Add installment citi v3.1.1
omise/omise-java pull request #117
Opened 2020-09-30 07:22 UTC by ratchagarn

Need to add install citi to source type

2020-09-30 07:30 UTC, nuxzero requested changes

2020-09-30 07:30 UTC, nuxzero commented on src/main/java/co/omise/models/SourceType.java
> +    InstCiti
Missed `,` at the trail. 🙂

2020-09-30 07:46 UTC, nuxzero approved these changes

2020-10-05 08:39 UTC, merged

2020-10-08 11:14 UTC, rezigned commented
Ah, this PR missed the `toString` 
part https://github.com/omise/omise-java/blob/28184be33917150111ee1c36957084103450fc49/src/main/java/co/omise/models/SourceType.java#L47-L51